name: Publish Docker image by tag
on:
  push:
    tags:
      - v*
jobs:
  docker:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Login DockerHub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ github.repository_owner }} --password-stdin

      - name: Set image tag
        run: |
          # use tag for image_tag, 'v1.2.3' -> '1.2.3'
          IMAGE_TAG=${GITHUB_REF##*/v}
          echo ::set-env name=IMAGE_TAG::${IMAGE_TAG}

      - name: Build and Publish
        run: |
          KUBECTL_VERSION=$(<kubectl-version)
          KUSTOMIZE_VERSION=$(<kustomize-version)
          SOPS_VERSION=$(<sops-version)
          docker buildx build \
            --build-arg KUBECTL_VERSION=$KUBECTL_VERSION \
            --build-arg KUSTOMIZE_VERSION=$KUSTOMIZE_VERSION \
            --build-arg SOPS_VERSION=$SOPS_VERSION \
            --push \
            --platform linux/arm/v7,linux/amd64 \
            -t ${{ github.repository }}:latest \
            -t ${{ github.repository }}:${IMAGE_TAG} .
